<?phprequire_once('api/Simpla.php');
class ArtPay extends Simpla{		public function checkout_form($order_id, $button_text = null)
	{		if(empty($button_text))			$button_text = 'Перейти к оплате';
		$order = $this->orders->get_order((int)$order_id);		$payment_method = $this->payment->get_payment_method($order->payment_method_id);		$payment_currency = $this->money->get_currency(intval($payment_method->currency_id));		$payment_settings = $this->payment->get_payment_settings($payment_method->id);
		$price = round($this->money->convert($order->total_price, $payment_method->currency_id, false), 2);				//собираем данные для отправки на сервер ArtPay
		$ap_data['ap_storeid'] = $payment_settings['ap_storeid'];		$ap_data['ap_order_num'] = $order_id;		$ap_data['ap_invoice_desc'] = 'Оплата заказа #' . $order_id;		$ap_data['ap_currency'] = $payment_currency->code;		$ap_data['ap_client_dt'] = time();		$ap_data['ap_amount'] = $price;		$ap_data['ap_test'] = $payment_settings['ap_test'];		$ap_data['ap_signature'] = $this->getSignature($ap_data, $payment_settings['artpay_secret1']);				if ($ap_data['ap_test'])			$action = 'https://gateway-sandbox-artpay.dev-3c.by/create/';		else			$action = 'https://engine.artpay.by/create/';		
		// описание заказа		$button =	'<form action="'.$action.'" method="POST"/>'.					'<input type="hidden" name="ap_storeid" value="'.$payment_settings['ap_storeid'].'" />'.					'<input type="hidden" name="ap_order_num" value="'.$ap_data['ap_order_num'].'" />'.					'<input type="hidden" name="ap_invoice_desc" value="'.$ap_data['ap_invoice_desc'].'" />'.					'<input type="hidden" name="ap_currency" value="'.$ap_data['ap_currency'].'" />'.					'<input type="hidden" name="ap_client_dt" value="'.$ap_data['ap_client_dt'].'" />'.					'<input type="hidden" name="ap_amount" value="'.$ap_data['ap_amount'].'" />'.					'<input type="hidden" name="ap_test" value="'.$ap_data['ap_test'].'" />'.					'<input type="hidden" name="ap_signature" value="'.$ap_data['ap_signature'].'" />'.
					'<input type=submit class=checkout_button value="'.$button_text.'">'.
					'</form>';
		return $button;	}		public function getSignature($data, $secret, $algo = 'sha512')	{		$string = '';		uksort($data, 'strnatcmp');		foreach ($data as $param => $value) {			$string .= $value . ';';		}					$string .= $secret;		return $key = hash($algo, $string);	}		public function checkSignature(/* array */ $data, $secret, $algo = 'sha512')	{		if (!isset($data['ap_signature']))			return false;		$addSignature = $data['ap_signature'];		unset($data['ap_signature']);					uksort($data, 'strnatcmp');		$string =  implode(';', $data) . ';' . $secret;					return hash($algo, $string) == $addSignature;	}}?>